Repository keep-network/coverage-pools, pull requests merged in 2022-12, with the labels that each got.

#221 Fix badges after change in shields.io syntax
  README.adoc
Labels: :book: documentation

#222 Change SemVer range for `@tenderly/hardhat-tenderly` dependency
  package.json
  yarn.lock
Labels: :shipit: deployment

#203 Updating deployment scripts for T cov pool
  .github/workflows/contracts.yml
  contracts/Auction.sol
  contracts/AuctionBidder.sol
  contracts/Auctioneer.sol
  contracts/RiskManagerV1.sol
  contracts/SignerBondsManualSwap.sol
  contracts/SignerBondsUniswapV2.sol
  contracts/test/TestToken.sol
  deploy/00_resolve_t_token.ts
  deploy/01_deploy_underwriter_token.ts
  deploy/01_resolve_tbtc_token.ts
  deploy/02_deploy_asset_pool.ts
  deploy/02_resolve_tdt_token.ts
  deploy/03_deploy_coverage_pool.ts
  deploy/03_resolve_uniswap_v2_router.ts
  deploy/04_deploy_coverage_pool_beneficiary.ts
  deploy/05_approve_treasury_guild.ts
  deploy/06_transfer_ownership_to_t_council.ts
  deploy/07_deploy_auction_bidder.ts
  deploy/08_deploy_signer_bonds_manual_swap.ts
  deploy/09_deploy_signer_bonds_uniswap_v2.ts
  deploy/10_deploy_master_auction.ts
  deploy/11_deploy_risk_manager_v1.ts
  deploy/13_transfer_ownership_to_community.ts
  external/mainnet-v1/BatchedPhasedEscrow.json
  external/mainnet-v1/KeepToken.json
  external/mainnet-v1/TBTCDepositToken.json
  external/mainnet-v1/TBTCToken.json
  external/mainnet-v1/UniswapV2Router.json
  external/mainnet-v2/T.json
  hardhat.config.ts
Labels: :chains: solidity
